"""empty message

Revision ID: bece494937ff
Revises: d6190a038540
Create Date: 2019-08-24 20:23:07.706619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bece494937ff'
down_revision = 'd6190a038540'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channel_score', sa.Column('channel_id', sa.Integer(), nullable=True))
    op.add_column('channel_score', sa.Column('total', sa.Integer(), nullable=False))
    op.drop_constraint('channel_score_cid_fkey', 'channel_score', type_='foreignkey')
    op.create_foreign_key(None, 'channel_score', 'channel', ['channel_id'], ['id'])
    op.drop_column('channel_score', 'cid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channel_score', sa.Column('cid', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'channel_score', type_='foreignkey')
    op.create_foreign_key('channel_score_cid_fkey', 'channel_score', 'channel', ['cid'], ['id'])
    op.drop_column('channel_score', 'total')
    op.drop_column('channel_score', 'channel_id')
    # ### end Alembic commands ###
