"""empty message

Revision ID: d6190a038540
Revises: e1311f15acf9
Create Date: 2019-08-24 18:42:32.855051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6190a038540'
down_revision = 'e1311f15acf9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_score', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint('user_score_uid_fkey', 'user_score', type_='foreignkey')
    op.create_foreign_key(None, 'user_score', 'user', ['user_id'], ['id'])
    op.drop_column('user_score', 'uid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_score', sa.Column('uid', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user_score', type_='foreignkey')
    op.create_foreign_key('user_score_uid_fkey', 'user_score', 'user', ['uid'], ['id'])
    op.drop_column('user_score', 'user_id')
    # ### end Alembic commands ###
